service: nest-lambda-api
frameworkVersion: '3'

plugins:
  - serverless-offline

provider: 
  name: aws
  runtime: nodejs16.x
  region: us-east-2
  timeout: 30
  memorySize: 512
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_ENV: ${self:provider.stage}
    APP_NAME: nest-lambda
    LOG_LEVEL: debug
    DB_HOST: ${self:custom.settings.${self:provider.stage}.DB_HOST}
    DB_NAME: ${self:custom.settings.${self:provider.stage}.DB_NAME}
    DB_PASSWORD: ${ssm:/nest/${self:provider.stage}/db/password}

functions:
  main: 
    handler: dist/lambda.handler
    events: 
      - httpApi:
          path: /{proxy+}
          method: ANY

custom:
  settings:
    dev:
      DB_HOST: localhost
      DB_NAME: test_db
    prod:
      DB_HOST: cluster.mongo.aws
      DB_NAME: prod_db
